#!/bin/bash

# binary path
name=es-kas
plugin=/usr/local/Cellar/elasticsearch/1.3.4/bin/plugin

echo "Trying to remove plugin..."
$plugin --remove $name

echo "Installing plugin..."
$plugin --url file:./target/releases/es-kas-0.1-SNAPSHOT-plugin.zip --install $name --verbose